# Generated by Django 2.0 on 2019-08-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=250)),
                ('marca', models.CharField(max_length=250)),
                ('cor', models.CharField(max_length=250)),
                ('qtd_disponivel', models.IntegerField(default=0)),
                ('qtd_min_disponivel', models.IntegerField(default=0)),
                ('pco_custo', models.FloatField()),
                ('pco_venda', models.FloatField()),
                ('dt_ultima_compra', models.DateField(default='1900-01-01')),
            ],
        ),
    ]
