# Generated by Django 2.0 on 2019-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250)),
                ('preco', models.FloatField()),
                ('produto', models.CharField(max_length=250)),
                ('disponibilidade', models.BooleanField()),
                ('tm_execucao', models.TimeField()),
            ],
        ),
    ]
