# Generated by Django 2.0 on 2019-08-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190518_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default='12345678', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='redes',
            field=models.CharField(default='instagram', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(default='yoda', max_length=250),
            preserve_default=False,
        ),
    ]
