# Generated by Django 2.0 on 2019-09-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
        ('clientes', '0004_cliente_dt_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('valor_pagamento', models.FloatField()),
                ('dt_pagamento', models.DateField(default='1900-01-01')),
                ('status', models.CharField(default='Aberto', max_length=10)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('cod_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Servico')),
            ],
        ),
    ]
